/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangAppRouteImport } from './routes/$lang/app'
import { Route as LangConfidentialiteRouteImport } from './routes/$lang/confidentialite'
import { Route as LangConnexionRouteImport } from './routes/$lang/connexion'
import { Route as LangDesignRouteImport } from './routes/$lang/design'
import { Route as LangMentionsLegalesRouteImport } from './routes/$lang/mentions-legales'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangAdminOrganisationsRouteImport } from './routes/$lang/admin/organisations'
import { Route as LangAdminProspectsRouteImport } from './routes/$lang/admin/prospects'
import { Route as LangAppIndexRouteImport } from './routes/$lang/app/index'
import { Route as LangAppAbonnementRouteImport } from './routes/$lang/app/abonnement'
import { Route as LangAppAlertesRouteImport } from './routes/$lang/app/alertes'
import { Route as LangAppAmendesRouteImport } from './routes/$lang/app/amendes'
import { Route as LangAppReglagesRouteImport } from './routes/$lang/app/reglages'
import { Route as LangAppSuiviRouteImport } from './routes/$lang/app/suivi'
import { Route as LangInvitationInvitationIdRouteImport } from './routes/$lang/invitation.$invitationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangAppClientsIndexRouteImport } from './routes/$lang/app/clients/index'
import { Route as LangAppClientsNouveauRouteImport } from './routes/$lang/app/clients/nouveau'
import { Route as LangAppContratsIndexRouteImport } from './routes/$lang/app/contrats/index'
import { Route as LangAppContratsContractIdRouteImport } from './routes/$lang/app/contrats/$contractId'
import { Route as LangAppContratsNouveauRouteImport } from './routes/$lang/app/contrats/nouveau'
import { Route as LangAppVehiculesIndexRouteImport } from './routes/$lang/app/vehicules/index'
import { Route as LangAppVehiculesVehicleIdRouteImport } from './routes/$lang/app/vehicules/$vehicleId'
import { Route as LangAppVehiculesNouveauRouteImport } from './routes/$lang/app/vehicules/nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangAppRoute = LangAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LangRoute,
} as any)
const LangConfidentialiteRoute = LangConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => LangRoute,
} as any)
const LangConnexionRoute = LangConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => LangRoute,
} as any)
const LangDesignRoute = LangDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => LangRoute,
} as any)
const LangMentionsLegalesRoute = LangMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminOrganisationsRoute = LangAdminOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminProspectsRoute = LangAdminProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAppIndexRoute = LangAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppAbonnementRoute = LangAppAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppAlertesRoute = LangAppAlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppAmendesRoute = LangAppAmendesRouteImport.update({
  id: '/amendes',
  path: '/amendes',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppReglagesRoute = LangAppReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppSuiviRoute = LangAppSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => LangAppRoute,
} as any)
const LangInvitationInvitationIdRoute =
  LangInvitationInvitationIdRouteImport.update({
    id: '/invitation/$invitationId',
    path: '/invitation/$invitationId',
    getParentRoute: () => LangRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAppClientsIndexRoute = LangAppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppClientsNouveauRoute = LangAppClientsNouveauRouteImport.update({
  id: '/clients/nouveau',
  path: '/clients/nouveau',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppContratsIndexRoute = LangAppContratsIndexRouteImport.update({
  id: '/contrats/',
  path: '/contrats/',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppContratsContractIdRoute =
  LangAppContratsContractIdRouteImport.update({
    id: '/contrats/$contractId',
    path: '/contrats/$contractId',
    getParentRoute: () => LangAppRoute,
  } as any)
const LangAppContratsNouveauRoute = LangAppContratsNouveauRouteImport.update({
  id: '/contrats/nouveau',
  path: '/contrats/nouveau',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppVehiculesIndexRoute = LangAppVehiculesIndexRouteImport.update({
  id: '/vehicules/',
  path: '/vehicules/',
  getParentRoute: () => LangAppRoute,
} as any)
const LangAppVehiculesVehicleIdRoute =
  LangAppVehiculesVehicleIdRouteImport.update({
    id: '/vehicules/$vehicleId',
    path: '/vehicules/$vehicleId',
    getParentRoute: () => LangAppRoute,
  } as any)
const LangAppVehiculesNouveauRoute = LangAppVehiculesNouveauRouteImport.update({
  id: '/vehicules/nouveau',
  path: '/vehicules/nouveau',
  getParentRoute: () => LangAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/app': typeof LangAppRouteWithChildren
  '/$lang/confidentialite': typeof LangConfidentialiteRoute
  '/$lang/connexion': typeof LangConnexionRoute
  '/$lang/design': typeof LangDesignRoute
  '/$lang/mentions-legales': typeof LangMentionsLegalesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/organisations': typeof LangAdminOrganisationsRoute
  '/$lang/admin/prospects': typeof LangAdminProspectsRoute
  '/$lang/app/abonnement': typeof LangAppAbonnementRoute
  '/$lang/app/alertes': typeof LangAppAlertesRoute
  '/$lang/app/amendes': typeof LangAppAmendesRoute
  '/$lang/app/reglages': typeof LangAppReglagesRoute
  '/$lang/app/suivi': typeof LangAppSuiviRoute
  '/$lang/invitation/$invitationId': typeof LangInvitationInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/app/': typeof LangAppIndexRoute
  '/$lang/app/clients/nouveau': typeof LangAppClientsNouveauRoute
  '/$lang/app/contrats/$contractId': typeof LangAppContratsContractIdRoute
  '/$lang/app/contrats/nouveau': typeof LangAppContratsNouveauRoute
  '/$lang/app/vehicules/$vehicleId': typeof LangAppVehiculesVehicleIdRoute
  '/$lang/app/vehicules/nouveau': typeof LangAppVehiculesNouveauRoute
  '/$lang/app/clients/': typeof LangAppClientsIndexRoute
  '/$lang/app/contrats/': typeof LangAppContratsIndexRoute
  '/$lang/app/vehicules/': typeof LangAppVehiculesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/confidentialite': typeof LangConfidentialiteRoute
  '/$lang/connexion': typeof LangConnexionRoute
  '/$lang/design': typeof LangDesignRoute
  '/$lang/mentions-legales': typeof LangMentionsLegalesRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin/organisations': typeof LangAdminOrganisationsRoute
  '/$lang/admin/prospects': typeof LangAdminProspectsRoute
  '/$lang/app/abonnement': typeof LangAppAbonnementRoute
  '/$lang/app/alertes': typeof LangAppAlertesRoute
  '/$lang/app/amendes': typeof LangAppAmendesRoute
  '/$lang/app/reglages': typeof LangAppReglagesRoute
  '/$lang/app/suivi': typeof LangAppSuiviRoute
  '/$lang/invitation/$invitationId': typeof LangInvitationInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/app': typeof LangAppIndexRoute
  '/$lang/app/clients/nouveau': typeof LangAppClientsNouveauRoute
  '/$lang/app/contrats/$contractId': typeof LangAppContratsContractIdRoute
  '/$lang/app/contrats/nouveau': typeof LangAppContratsNouveauRoute
  '/$lang/app/vehicules/$vehicleId': typeof LangAppVehiculesVehicleIdRoute
  '/$lang/app/vehicules/nouveau': typeof LangAppVehiculesNouveauRoute
  '/$lang/app/clients': typeof LangAppClientsIndexRoute
  '/$lang/app/contrats': typeof LangAppContratsIndexRoute
  '/$lang/app/vehicules': typeof LangAppVehiculesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/app': typeof LangAppRouteWithChildren
  '/$lang/confidentialite': typeof LangConfidentialiteRoute
  '/$lang/connexion': typeof LangConnexionRoute
  '/$lang/design': typeof LangDesignRoute
  '/$lang/mentions-legales': typeof LangMentionsLegalesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/organisations': typeof LangAdminOrganisationsRoute
  '/$lang/admin/prospects': typeof LangAdminProspectsRoute
  '/$lang/app/abonnement': typeof LangAppAbonnementRoute
  '/$lang/app/alertes': typeof LangAppAlertesRoute
  '/$lang/app/amendes': typeof LangAppAmendesRoute
  '/$lang/app/reglages': typeof LangAppReglagesRoute
  '/$lang/app/suivi': typeof LangAppSuiviRoute
  '/$lang/invitation/$invitationId': typeof LangInvitationInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/app/': typeof LangAppIndexRoute
  '/$lang/app/clients/nouveau': typeof LangAppClientsNouveauRoute
  '/$lang/app/contrats/$contractId': typeof LangAppContratsContractIdRoute
  '/$lang/app/contrats/nouveau': typeof LangAppContratsNouveauRoute
  '/$lang/app/vehicules/$vehicleId': typeof LangAppVehiculesVehicleIdRoute
  '/$lang/app/vehicules/nouveau': typeof LangAppVehiculesNouveauRoute
  '/$lang/app/clients/': typeof LangAppClientsIndexRoute
  '/$lang/app/contrats/': typeof LangAppContratsIndexRoute
  '/$lang/app/vehicules/': typeof LangAppVehiculesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/app'
    | '/$lang/confidentialite'
    | '/$lang/connexion'
    | '/$lang/design'
    | '/$lang/mentions-legales'
    | '/$lang/'
    | '/$lang/admin/organisations'
    | '/$lang/admin/prospects'
    | '/$lang/app/abonnement'
    | '/$lang/app/alertes'
    | '/$lang/app/amendes'
    | '/$lang/app/reglages'
    | '/$lang/app/suivi'
    | '/$lang/invitation/$invitationId'
    | '/api/auth/$'
    | '/$lang/admin/'
    | '/$lang/app/'
    | '/$lang/app/clients/nouveau'
    | '/$lang/app/contrats/$contractId'
    | '/$lang/app/contrats/nouveau'
    | '/$lang/app/vehicules/$vehicleId'
    | '/$lang/app/vehicules/nouveau'
    | '/$lang/app/clients/'
    | '/$lang/app/contrats/'
    | '/$lang/app/vehicules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/confidentialite'
    | '/$lang/connexion'
    | '/$lang/design'
    | '/$lang/mentions-legales'
    | '/$lang'
    | '/$lang/admin/organisations'
    | '/$lang/admin/prospects'
    | '/$lang/app/abonnement'
    | '/$lang/app/alertes'
    | '/$lang/app/amendes'
    | '/$lang/app/reglages'
    | '/$lang/app/suivi'
    | '/$lang/invitation/$invitationId'
    | '/api/auth/$'
    | '/$lang/admin'
    | '/$lang/app'
    | '/$lang/app/clients/nouveau'
    | '/$lang/app/contrats/$contractId'
    | '/$lang/app/contrats/nouveau'
    | '/$lang/app/vehicules/$vehicleId'
    | '/$lang/app/vehicules/nouveau'
    | '/$lang/app/clients'
    | '/$lang/app/contrats'
    | '/$lang/app/vehicules'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/app'
    | '/$lang/confidentialite'
    | '/$lang/connexion'
    | '/$lang/design'
    | '/$lang/mentions-legales'
    | '/$lang/'
    | '/$lang/admin/organisations'
    | '/$lang/admin/prospects'
    | '/$lang/app/abonnement'
    | '/$lang/app/alertes'
    | '/$lang/app/amendes'
    | '/$lang/app/reglages'
    | '/$lang/app/suivi'
    | '/$lang/invitation/$invitationId'
    | '/api/auth/$'
    | '/$lang/admin/'
    | '/$lang/app/'
    | '/$lang/app/clients/nouveau'
    | '/$lang/app/contrats/$contractId'
    | '/$lang/app/contrats/nouveau'
    | '/$lang/app/vehicules/$vehicleId'
    | '/$lang/app/vehicules/nouveau'
    | '/$lang/app/clients/'
    | '/$lang/app/contrats/'
    | '/$lang/app/vehicules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/app': {
      id: '/$lang/app'
      path: '/app'
      fullPath: '/$lang/app'
      preLoaderRoute: typeof LangAppRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/confidentialite': {
      id: '/$lang/confidentialite'
      path: '/confidentialite'
      fullPath: '/$lang/confidentialite'
      preLoaderRoute: typeof LangConfidentialiteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/connexion': {
      id: '/$lang/connexion'
      path: '/connexion'
      fullPath: '/$lang/connexion'
      preLoaderRoute: typeof LangConnexionRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/design': {
      id: '/$lang/design'
      path: '/design'
      fullPath: '/$lang/design'
      preLoaderRoute: typeof LangDesignRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/mentions-legales': {
      id: '/$lang/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$lang/mentions-legales'
      preLoaderRoute: typeof LangMentionsLegalesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/organisations': {
      id: '/$lang/admin/organisations'
      path: '/organisations'
      fullPath: '/$lang/admin/organisations'
      preLoaderRoute: typeof LangAdminOrganisationsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/prospects': {
      id: '/$lang/admin/prospects'
      path: '/prospects'
      fullPath: '/$lang/admin/prospects'
      preLoaderRoute: typeof LangAdminProspectsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/app/': {
      id: '/$lang/app/'
      path: '/'
      fullPath: '/$lang/app/'
      preLoaderRoute: typeof LangAppIndexRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/abonnement': {
      id: '/$lang/app/abonnement'
      path: '/abonnement'
      fullPath: '/$lang/app/abonnement'
      preLoaderRoute: typeof LangAppAbonnementRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/alertes': {
      id: '/$lang/app/alertes'
      path: '/alertes'
      fullPath: '/$lang/app/alertes'
      preLoaderRoute: typeof LangAppAlertesRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/amendes': {
      id: '/$lang/app/amendes'
      path: '/amendes'
      fullPath: '/$lang/app/amendes'
      preLoaderRoute: typeof LangAppAmendesRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/reglages': {
      id: '/$lang/app/reglages'
      path: '/reglages'
      fullPath: '/$lang/app/reglages'
      preLoaderRoute: typeof LangAppReglagesRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/suivi': {
      id: '/$lang/app/suivi'
      path: '/suivi'
      fullPath: '/$lang/app/suivi'
      preLoaderRoute: typeof LangAppSuiviRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/invitation/$invitationId': {
      id: '/$lang/invitation/$invitationId'
      path: '/invitation/$invitationId'
      fullPath: '/$lang/invitation/$invitationId'
      preLoaderRoute: typeof LangInvitationInvitationIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/app/clients/': {
      id: '/$lang/app/clients/'
      path: '/clients'
      fullPath: '/$lang/app/clients/'
      preLoaderRoute: typeof LangAppClientsIndexRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/clients/nouveau': {
      id: '/$lang/app/clients/nouveau'
      path: '/clients/nouveau'
      fullPath: '/$lang/app/clients/nouveau'
      preLoaderRoute: typeof LangAppClientsNouveauRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/contrats/': {
      id: '/$lang/app/contrats/'
      path: '/contrats'
      fullPath: '/$lang/app/contrats/'
      preLoaderRoute: typeof LangAppContratsIndexRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/contrats/$contractId': {
      id: '/$lang/app/contrats/$contractId'
      path: '/contrats/$contractId'
      fullPath: '/$lang/app/contrats/$contractId'
      preLoaderRoute: typeof LangAppContratsContractIdRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/contrats/nouveau': {
      id: '/$lang/app/contrats/nouveau'
      path: '/contrats/nouveau'
      fullPath: '/$lang/app/contrats/nouveau'
      preLoaderRoute: typeof LangAppContratsNouveauRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/vehicules/': {
      id: '/$lang/app/vehicules/'
      path: '/vehicules'
      fullPath: '/$lang/app/vehicules/'
      preLoaderRoute: typeof LangAppVehiculesIndexRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/vehicules/$vehicleId': {
      id: '/$lang/app/vehicules/$vehicleId'
      path: '/vehicules/$vehicleId'
      fullPath: '/$lang/app/vehicules/$vehicleId'
      preLoaderRoute: typeof LangAppVehiculesVehicleIdRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/app/vehicules/nouveau': {
      id: '/$lang/app/vehicules/nouveau'
      path: '/vehicules/nouveau'
      fullPath: '/$lang/app/vehicules/nouveau'
      preLoaderRoute: typeof LangAppVehiculesNouveauRouteImport
      parentRoute: typeof LangAppRoute
    }
  }
}

interface LangAdminRouteChildren {
  LangAdminOrganisationsRoute: typeof LangAdminOrganisationsRoute
  LangAdminProspectsRoute: typeof LangAdminProspectsRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
}

const LangAdminRouteChildren: LangAdminRouteChildren = {
  LangAdminOrganisationsRoute: LangAdminOrganisationsRoute,
  LangAdminProspectsRoute: LangAdminProspectsRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
}

const LangAdminRouteWithChildren = LangAdminRoute._addFileChildren(
  LangAdminRouteChildren,
)

interface LangAppRouteChildren {
  LangAppAbonnementRoute: typeof LangAppAbonnementRoute
  LangAppAlertesRoute: typeof LangAppAlertesRoute
  LangAppAmendesRoute: typeof LangAppAmendesRoute
  LangAppReglagesRoute: typeof LangAppReglagesRoute
  LangAppSuiviRoute: typeof LangAppSuiviRoute
  LangAppIndexRoute: typeof LangAppIndexRoute
  LangAppClientsNouveauRoute: typeof LangAppClientsNouveauRoute
  LangAppContratsContractIdRoute: typeof LangAppContratsContractIdRoute
  LangAppContratsNouveauRoute: typeof LangAppContratsNouveauRoute
  LangAppVehiculesVehicleIdRoute: typeof LangAppVehiculesVehicleIdRoute
  LangAppVehiculesNouveauRoute: typeof LangAppVehiculesNouveauRoute
  LangAppClientsIndexRoute: typeof LangAppClientsIndexRoute
  LangAppContratsIndexRoute: typeof LangAppContratsIndexRoute
  LangAppVehiculesIndexRoute: typeof LangAppVehiculesIndexRoute
}

const LangAppRouteChildren: LangAppRouteChildren = {
  LangAppAbonnementRoute: LangAppAbonnementRoute,
  LangAppAlertesRoute: LangAppAlertesRoute,
  LangAppAmendesRoute: LangAppAmendesRoute,
  LangAppReglagesRoute: LangAppReglagesRoute,
  LangAppSuiviRoute: LangAppSuiviRoute,
  LangAppIndexRoute: LangAppIndexRoute,
  LangAppClientsNouveauRoute: LangAppClientsNouveauRoute,
  LangAppContratsContractIdRoute: LangAppContratsContractIdRoute,
  LangAppContratsNouveauRoute: LangAppContratsNouveauRoute,
  LangAppVehiculesVehicleIdRoute: LangAppVehiculesVehicleIdRoute,
  LangAppVehiculesNouveauRoute: LangAppVehiculesNouveauRoute,
  LangAppClientsIndexRoute: LangAppClientsIndexRoute,
  LangAppContratsIndexRoute: LangAppContratsIndexRoute,
  LangAppVehiculesIndexRoute: LangAppVehiculesIndexRoute,
}

const LangAppRouteWithChildren =
  LangAppRoute._addFileChildren(LangAppRouteChildren)

interface LangRouteChildren {
  LangAdminRoute: typeof LangAdminRouteWithChildren
  LangAppRoute: typeof LangAppRouteWithChildren
  LangConfidentialiteRoute: typeof LangConfidentialiteRoute
  LangConnexionRoute: typeof LangConnexionRoute
  LangDesignRoute: typeof LangDesignRoute
  LangMentionsLegalesRoute: typeof LangMentionsLegalesRoute
  LangIndexRoute: typeof LangIndexRoute
  LangInvitationInvitationIdRoute: typeof LangInvitationInvitationIdRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAdminRoute: LangAdminRouteWithChildren,
  LangAppRoute: LangAppRouteWithChildren,
  LangConfidentialiteRoute: LangConfidentialiteRoute,
  LangConnexionRoute: LangConnexionRoute,
  LangDesignRoute: LangDesignRoute,
  LangMentionsLegalesRoute: LangMentionsLegalesRoute,
  LangIndexRoute: LangIndexRoute,
  LangInvitationInvitationIdRoute: LangInvitationInvitationIdRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
